WELCOME TO DASH
Got bored so I went ahead and modified the entire script to use dash
instead of bash!! Going to go and run some performance tests (There
could be zero difference, but that's okay)

diff --git a/examples/report b/examples/report
--- a/examples/report
+++ b/examples/report
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 echo -n "Position: "
-ansi --report-position || echo "Error"
+../ansi --report-position || echo "Error"
 echo -n "Icon: "
-ansi --report-icon || echo "Error"
+../ansi --report-icon || echo "Error"
 echo -n "Screen Chars: "
-ansi --report-screen-chars || echo "Error"
+../ansi --report-screen-chars || echo "Error"
 echo -n "Title: "
-ansi --report-title || echo "Error"
+../ansi --report-title || echo "Error"
 echo -n "Window Chars: "
-ansi --report-window-chars || echo "Error"
+../ansi --report-window-chars || echo "Error"
 echo -n "Window Pixels: "
-ansi --report-window-pixels || echo "Error"
+../ansi --report-window-pixels || echo "Error"
 echo -n "Window Position: "
-ansi --report-window-position || echo "Error"
+../ansi --report-window-position || echo "Error"
 echo -n "Window State: "
-ansi --report-window-state || echo "Error"
+../ansi --report-window-state || echo "Error"
 
 # NOTE: This won't work
 # echo "Position: $(ansi --report-position)"
